path: C:/Users/Gold/Desktop/yolov8_gpu/3_img_segmentation/car_part_dataset

train: images/train
val: images/val
test: images/test



names: ['back_bumper', 'back_door', 'back_glass', 'back_light', 
        'front_bumper', 'front_door', 'front_glass', 'front_light', 
        'hood']